[package]
description = "S3 server using durable instances."

[fs]
"/fe" = "./src/fe"
"/bucket-1" = "./bucket-1"
"/bucket-2" = "./bucket-2"

[[module]]
name = "s3-server"
source = "./target/wasm32-wasmer-wasi/debug/s3-server.wasm"

[[command]]
name = "s3-server"
module = "s3-server"
runner = "wasi"
